# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Aude KOUASSY\venv\Projet_Vac\affichage_bi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3
import photos_rc

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(956, 662)
        self.bground = QtWidgets.QFrame(Dialog)
        self.bground.setGeometry(QtCore.QRect(100, 30, 801, 81))
        self.bground.setStyleSheet("QFrame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(116, 0, 81, 255), stop:1 rgba(102, 64, 255, 255));\n"
"border-radius:40px;}")
        self.bground.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bground.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bground.setObjectName("bground")
        
        self.app_name = QtWidgets.QLabel(self.bground)
        self.app_name.setGeometry(QtCore.QRect(310, 20, 161, 41))
        self.app_name.setStyleSheet("font: 30pt \"Forte\";\n"
"background:transparent;")
        self.app_name.setObjectName("app_name")
        
        self.acceuil = QtWidgets.QPushButton(self.bground)
        self.acceuil.setGeometry(QtCore.QRect(710, 10, 31, 23))
        self.acceuil.setStyleSheet("background:transparent;")
        self.acceuil.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/C:/Users/Aude KOUASSY/Desktop/icones/accueil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.acceuil.setIcon(icon)
        self.acceuil.setObjectName("acceuil")
        
        self.sortir = QtWidgets.QPushButton(self.bground)
        self.sortir.setGeometry(QtCore.QRect(740, 10, 31, 23))
        self.sortir.setStyleSheet("background:transparent;")
        self.sortir.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/C:/Users/Aude KOUASSY/Desktop/icones/effacer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sortir.setIcon(icon1)
        self.sortir.setObjectName("sortir")
        
        self.affichage = QtWidgets.QTableWidget(Dialog)
        self.affichage.setGeometry(QtCore.QRect(80, 110, 841, 451))
        self.affichage.setShowGrid(True)
        self.affichage.setGridStyle(QtCore.Qt.DotLine)
        self.affichage.setWordWrap(True)
        self.affichage.setRowCount(30)
        self.affichage.setColumnCount(8)
        self.affichage.setObjectName("affichage")
        item = QtWidgets.QTableWidgetItem()
        self.affichage.setItem(0, 0, item)
        
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(110, 100, 781, 541))
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(116, 0, 81, 255), stop:1 rgba(102, 64, 255, 255));\n"
"border-radius:20px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.valider = QtWidgets.QPushButton(self.frame)
        self.valider.setGeometry(QtCore.QRect(290, 470, 221, 61))
        self.valider.setStyleSheet("QPushButton{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(106, 0, 91, 255), stop:1 rgba(100, 60, 255, 255));\n"
"border-radius: 10px;\n"
"background-color:white;\n"
"font:10pt \"Verdana Pro Semibold\";\n"
"padding:18px;\n"
"}\n"
"QPushButton:hover{\n"
"border-top-color:#084870;\n"
"background:white;\n"
"color:#c910c9;\n"
"}\n"
"QPushButton:active{\n"
"border-top-color:#409ad6;\n"
"background:white;\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/C:/Users/Aude KOUASSY/Desktop/icones/cooche.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.valider.setIcon(icon2)
        self.valider.setObjectName("valider")
        self.valider.clicked.connect(self.load_data)
        
        self.frame.raise_()
        self.bground.raise_()
        self.affichage.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Bino\'App - Liste des binomages"))
        
        Dialog.setWindowFlag(QtCore.Qt.FramelessWindowHint) #supprime l'affiche à outils de la fenetre
        Dialog.setAttribute(QtCore.Qt.WA_TranslucentBackground)  # supprime le background de la fenetre
        self.app_name.setText(_translate("Dialog", "Bino\'App"))
        __sortingEnabled = self.affichage.isSortingEnabled()
        self.affichage.setSortingEnabled(False)
        self.affichage.setSortingEnabled(__sortingEnabled)
        self.valider.setText(_translate("Dialog", "Afficher le binomage"))
        # noms des differentes colonnes
        self.affichage.setHorizontalHeaderLabels(["Matricule", "Nom Parrain","Prénoms","Classe","Matricule","Nom Filleul","Prénoms","Classe"])

    def load_data(self):
        conn = sqlite3.connect('Binoap.db')
        cur = conn.cursor()  
        try:
            sql = "SELECT PARRAIN_MARRAINE.Matricule, PARRAIN_MARRAINE.Nom,PARRAIN_MARRAINE.Prenom,PARRAIN_MARRAINE.Classe, FILEULE.Id_fileule, FILEULE.Nom_F,FILEULE.Prenom_F,FILEULE.Classe_F FROM FILEULE,PARRAIN_MARRAINE WHERE FILEULE.Matricule = PARRAIN_MARRAINE.Matricule ORDER BY PARRAIN_MARRAINE.Nom ASC"
            requete = cur.execute(sql)
            conn.commit()
            self.affichage.setRowCount(0)
            for row_num, row_data in enumerate (requete):
                self.affichage.insertRow(row_num)
                for column_num,data in enumerate (row_data):
                    self.affichage.setItem(row_num,column_num,QtWidgets.QTableWidgetItem(str(data)))
        except:
            print("salut")
            
        conn.close()
        
      
'''if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
'''