# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Aude KOUASSY\venv\Projet_Vac\error.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(564, 482)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(110, 50, 251, 391))
        self.frame.setStyleSheet("QWidget#frame{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(116, 0, 81, 255), stop:1 rgba(102, 64, 255, 255));\n"
"border-radius:40px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 350, 101, 20))
        self.label.setStyleSheet("\n"
"font: 8pt \"Bradley Hand ITC\";\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.app_name = QtWidgets.QLabel(self.frame)
        self.app_name.setGeometry(QtCore.QRect(60, 50, 121, 41))
        self.app_name.setStyleSheet("font: 22pt \"Forte\";")
        self.app_name.setObjectName("app_name")
        
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(30, 140, 181, 161))
        self.frame_2.setStyleSheet("background-color:white;\n"
"border-radius:14px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 161, 131))
        self.label_3.setStyleSheet("position: relative;\n"
"font: 15pt \"Sandy Kids\";\n")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 130, 71, 31))
        self.label_2.setStyleSheet("background-color: rgb(244, 217, 255);\n"
"font: 14pt \"TAKE CUTE\";\n"
"border-radius:10px;")
        self.label_2.setObjectName("label_2")
        
        self.valider = QtWidgets.QPushButton(self.frame)
        self.valider.setGeometry(QtCore.QRect(60, 320, 121, 23))
        self.valider.setStyleSheet("QPushButton{\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(106, 0, 91, 255), stop:1 rgba(100, 60, 255, 255));\n"
"border-radius: 10px;\n"
"background-color:white;\n"
"font:10pt \"Verdana Pro Semibold\";\n"
"padding:18px;\n"
"}\n"
"QPushButton:hover{\n"
"border-top-color:#084870;\n"
"background:white;\n"
"color:#c910c9;\n"
"}\n"
"QPushButton:active{\n"
"border-top-color:#409ad6;\n"
"background:white;\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/C:/Users/Aude KOUASSY/Desktop/icones/cooche.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.valider.setIcon(icon2)
        self.valider.setObjectName("valider")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Message d'erreur"))
        self.label.setText(_translate("Dialog", "Modern GUI v-2021"))
        self.app_name.setText(_translate("Dialog", "Bino\'App"))
        self.label_3.setText(_translate("Dialog", "Matricule non trouvé"))
        self.label_2.setText(_translate("Dialog", " ERREUR"))
        self.valider.setText(_translate("Dialog", "Compris"))
import photos_rc



